package com.neu.dimple.springbootapplication.persistance.dynamodbpersistance;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import net.bytebuddy.implementation.bind.annotation.Default;
import org.springframework.beans.factory.annotation.Value;

import java.time.Instant;

/**
 * @author Dimpleben Kanjibhai Patel
 */
@DynamoDBTable(tableName = "UserTokenTable")
public class UserEmailToken {

    long now = Instant.now().getEpochSecond() ;
    long ttl = 60;

    @DynamoDBHashKey(attributeName = "Token")
    @DynamoDBAutoGeneratedKey
    private String token;

    @DynamoDBRangeKey(attributeName = "Email")
    private String email;

    @DynamoDBAttribute
//    @Value("${now + ttl}")
    private long expiration_time;

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public long getExpiration_time() {
        return expiration_time;
    }

    public void setExpiration_time(long expiration_time) {
        this.expiration_time = ttl + now;
    }
}
